// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: proto/sample-manager.proto

package sample_manager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SampleManagerClient is the client API for SampleManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SampleManagerClient interface {
	// Sends a request to get a sample item ID based on CLM segments and item ID.
	GetSampleItemID(ctx context.Context, in *GetSampleItemIDRequest, opts ...grpc.CallOption) (*GetSampleItemIDResponse, error)
}

type sampleManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewSampleManagerClient(cc grpc.ClientConnInterface) SampleManagerClient {
	return &sampleManagerClient{cc}
}

func (c *sampleManagerClient) GetSampleItemID(ctx context.Context, in *GetSampleItemIDRequest, opts ...grpc.CallOption) (*GetSampleItemIDResponse, error) {
	out := new(GetSampleItemIDResponse)
	err := c.cc.Invoke(ctx, "/SampleManager/GetSampleItemID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SampleManagerServer is the server API for SampleManager service.
// All implementations must embed UnimplementedSampleManagerServer
// for forward compatibility
type SampleManagerServer interface {
	// Sends a request to get a sample item ID based on CLM segments and item ID.
	GetSampleItemID(context.Context, *GetSampleItemIDRequest) (*GetSampleItemIDResponse, error)
	mustEmbedUnimplementedSampleManagerServer()
}

// UnimplementedSampleManagerServer must be embedded to have forward compatible implementations.
type UnimplementedSampleManagerServer struct {
}

func (UnimplementedSampleManagerServer) GetSampleItemID(context.Context, *GetSampleItemIDRequest) (*GetSampleItemIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSampleItemID not implemented")
}
func (UnimplementedSampleManagerServer) mustEmbedUnimplementedSampleManagerServer() {}

// UnsafeSampleManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SampleManagerServer will
// result in compilation errors.
type UnsafeSampleManagerServer interface {
	mustEmbedUnimplementedSampleManagerServer()
}

func RegisterSampleManagerServer(s grpc.ServiceRegistrar, srv SampleManagerServer) {
	s.RegisterService(&SampleManager_ServiceDesc, srv)
}

func _SampleManager_GetSampleItemID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSampleItemIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleManagerServer).GetSampleItemID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SampleManager/GetSampleItemID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleManagerServer).GetSampleItemID(ctx, req.(*GetSampleItemIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SampleManager_ServiceDesc is the grpc.ServiceDesc for SampleManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SampleManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SampleManager",
	HandlerType: (*SampleManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSampleItemID",
			Handler:    _SampleManager_GetSampleItemID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sample-manager.proto",
}
